import sublime, sublime_plugin

class PHPServerVarsCompletion(sublime_plugin.EventListener):
	def on_query_completions(self, view, prefix, locations):
		return [
			("$_SERVER\tDOCUMENT_ROOT", "_SERVER['DOCUMENT_ROOT']"),
			("$_SERVER\tHTTP_HOST", "_SERVER['HTTP_HOST']"),
			("$_SERVER\tSCRIPT_FILENAME", "_SERVER['SCRIPT_FILENAME']"),
			("$_SERVER\tREQUEST_URI", "_SERVER['REQUEST_URI']"),
			("$_SERVER\tSCRIPT_NAME", "_SERVER['SCRIPT_NAME']"),
			("$_SERVER\tPHP_SELF", "_SERVER['PHP_SELF']"),
			("$_SERVER\tHTTPS", "_SERVER['HTTPS']"),
			("$_SERVER\tHTTP_USER_AGENT", "_SERVER['HTTP_USER_AGENT']"),
			("$_SERVER\tHTTP_ACCEPT", "_SERVER['HTTP_ACCEPT']"),
			("$_SERVER\tHTTP_ACCEPT_LANGUAGE", "_SERVER['HTTP_ACCEPT_LANGUAGE']"),
			("$_SERVER\tHTTP_ACCEPT_ENCODING", "_SERVER['HTTP_ACCEPT_ENCODING']"),
			("$_SERVER\tHTTP_CONNECTION", "_SERVER['HTTP_CONNECTION']"),
			("$_SERVER\tPATH", "_SERVER['PATH']"),
			("$_SERVER\tSERVER_SIGNATUR", "_SERVER['SERVER_SIGNATUR']"),
			("$_SERVER\tSERVER_SOFTWARE", "_SERVER['SERVER_SOFTWARE']"),
			("$_SERVER\tSERVER_NAME", "_SERVER['SERVER_NAME']"),
			("$_SERVER\tSERVER_ADDR", "_SERVER['SERVER_ADDR']"),
			("$_SERVER\tSERVER_PORT", "_SERVER['SERVER_PORT']"),
			("$_SERVER\tREMOTE_ADDR", "_SERVER['REMOTE_ADDR']"),
			("$_SERVER\tSERVER_ADMIN", "_SERVER['SERVER_ADMIN']"),
			("$_SERVER\tREMOTE_PORT", "_SERVER['REMOTE_PORT']"),
			("$_SERVER\tGATEWAY_INTERFACE", "_SERVER['GATEWAY_INTERFACE']"),
			("$_SERVER\tSERVER_PROTOCOL", "_SERVER['SERVER_PROTOCOL']"),
			("$_SERVER\tREQUEST_METHOD", "_SERVER['REQUEST_METHOD']"),
			("$_SERVER\tQUERY_STRING", "_SERVER['QUERY_STRING']"),
			("$_SERVER\tREQUEST_TIME", "_SERVER['REQUEST_TIME']")
		]